language: java
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8

script:
  - sudo apt-get update
  - sudo apt-get install hugo
  - ./gradlew --stacktrace check generateWebsite

after_success:
  - bash <(curl -s https://codecov.io/bash)
