baseurl = "https://github.com/neuhalje/bouncy-gpg"
title = "Bouncy GPG"
author = "Jens Neuhalfen"
copyright = "Copyright (c) 2017 - , Jens Neuhalfen; all rights reserved."
canonifyurls = true
paginate = 3
theme = "docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]
